config/routes.rb
CarrierExample::Application.routes.draw do
  resources :your_scaffolds

end

app/models/your_scaffold.rb
class YourScaffold < ActiveRecord::Base
  attr_accessible :description, :image, :title

  mount_uploader :image, YourUploaderUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/your_scaffolds_controller.rb
class YourScaffoldsController < ApplicationController
  # GET /your_scaffolds
  # GET /your_scaffolds.json
  def index
    @your_scaffolds = YourScaffold.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @your_scaffolds }
    end
  end

  # GET /your_scaffolds/1
  # GET /your_scaffolds/1.json
  def show
    @your_scaffold = YourScaffold.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @your_scaffold }
    end
  end

  # GET /your_scaffolds/new
  # GET /your_scaffolds/new.json
  def new
    @your_scaffold = YourScaffold.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @your_scaffold }
    end
  end

  # GET /your_scaffolds/1/edit
  def edit
    @your_scaffold = YourScaffold.find(params[:id])
  end

  # POST /your_scaffolds
  # POST /your_scaffolds.json
  def create
    @your_scaffold = YourScaffold.new(params[:your_scaffold])

    respond_to do |format|
      if @your_scaffold.save
        format.html { redirect_to @your_scaffold, notice: 'Your scaffold was successfully created.' }
        format.json { render json: @your_scaffold, status: :created, location: @your_scaffold }
      else
        format.html { render action: "new" }
        format.json { render json: @your_scaffold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /your_scaffolds/1
  # PUT /your_scaffolds/1.json
  def update
    @your_scaffold = YourScaffold.find(params[:id])

    respond_to do |format|
      if @your_scaffold.update_attributes(params[:your_scaffold])
        format.html { redirect_to @your_scaffold, notice: 'Your scaffold was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @your_scaffold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /your_scaffolds/1
  # DELETE /your_scaffolds/1.json
  def destroy
    @your_scaffold = YourScaffold.find(params[:id])
    @your_scaffold.destroy

    respond_to do |format|
      format.html { redirect_to your_scaffolds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/your_scaffolds_helper.rb
module YourScaffoldsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarrierExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/your_scaffolds/_form.html.erb
<%= form_for @your_scaffold, html: { multipart: true } do |f| %>
  <% if @your_scaffold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@your_scaffold.errors.count, "error") %> prohibited this your_scaffold from being saved:</h2>

      <ul>
      <% @your_scaffold.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/your_scaffolds/edit.html.erb
<h1>Editing your_scaffold</h1>

<%= render 'form' %>

<%= link_to 'Show', @your_scaffold %> |
<%= link_to 'Back', your_scaffolds_path %>

app/views/your_scaffolds/index.html.erb
<h1>Listing your_scaffolds</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @your_scaffolds.each do |your_scaffold| %>
  <tr>
    <td><%= your_scaffold.title %></td>
    <td><%= your_scaffold.description %></td>
    <td><%= your_scaffold.image %></td>
    <td><%= link_to 'Show', your_scaffold %></td>
    <td><%= link_to 'Edit', edit_your_scaffold_path(your_scaffold) %></td>
    <td><%= link_to 'Destroy', your_scaffold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Your scaffold', new_your_scaffold_path %>

app/views/your_scaffolds/new.html.erb
<h1>New your_scaffold</h1>

<%= render 'form' %>

<%= link_to 'Back', your_scaffolds_path %>

app/views/your_scaffolds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @your_scaffold.title %>
</p>

<p>
  <b>Description:</b>
  <%= @your_scaffold.description %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @your_scaffold.image_url(:thumb) %>
</p>


<%= link_to 'Edit', edit_your_scaffold_path(@your_scaffold) %> |
<%= link_to 'Back', your_scaffolds_path %>